wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.0001
batch-size:
  value: 16
beta_1:
  value: 0.99
hidden_sizes:
  value: 32
n_epochs:
  value: 5
num_layer:
  value: 3
optimizer:
  value: sgd
weight-init:
  value: random
