wandb_version: 1

hidden_activations:
  desc: null
  value: tanh
init_strategy:
  desc: null
  value: he
loss_fn:
  desc: null
  value: cross_entropy
optimizer:
  desc: null
  value: nadam
learning_rate:
  desc: null
  value: 0.001
n_epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 16
alpha:
  desc: null
  value: 0.0001
beta_1:
  desc: null
  value: 0.9
beta_2:
  desc: null
  value: 0.995
regularizer:
  desc: null
  value: l1
hidden_sizes:
  desc: null
  value:
  - 128
  - 64
  - 32
epsilon:
  desc: null
  value: 1.0e-08
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715968514
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
