wandb_version: 1

activation:
  value: sigmoid
alpha:
  value: 0.0001
batch-size:
  value: 64
beta_1:
  value: 0.9
hidden_sizes:
  value: 128
loss_fn:
  value: cross_entropy
n_epochs:
  value: 10
num_layer:
  value: 3
optimizer:
  value: rmsprop
weight-init:
  value: Xavier
