wandb_version: 1

activation:
  value: sigmoid
alpha:
  value: 0.0001
batch-size:
  value: 64
beta_1:
  value: 0.9
hidden_sizes:
  value: 64.128
n_epochs:
  value: 5
num_layer:
  value: 4
optimizer:
  value: rmsprop
weight-init:
  value: Xavier
