wandb_version: 1

activation:
  value: ReLU
alpha:
  value: 0.001
batch_size:
  value: 32
beta1:
  value: 0.9
epochs:
  value: 5
hidden_sizes:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: sgd
weight_init:
  value: he
