wandb_version: 1

activation:
  value: sigmoid
alpha:
  value: 0.0001
batch_size:
  value: 64
beta1:
  value: 0.99
epochs:
  value: 5
hidden_sizes:
  value: 64
learning_rate:
  value: 1.0e-05
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: rmsprop
weight_init:
  value: random
