wandb_version: 1

activation:
  value: sigmoid
alpha:
  value: 0.0001
batch_size:
  value: 16
beta1:
  value: 0.9
epochs:
  value: 10
hidden_sizes:
  value: 32
learning_rate:
  value: 1.0e-05
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: sgd
weight_init:
  value: he
