wandb_version: 1

activation:
  value: ReLU
alpha:
  value: 0.001
batch_size:
  value: 32
beta1:
  value: 0.99
epochs:
  value: 10
hidden_sizes:
  value: 64
learning_rate:
  value: 1.0e-05
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: nadam
weight_init:
  value: he
