wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.0001
batch_size:
  value: 32
beta1:
  value: 0.99
epochs:
  value: 10
hidden_sizes:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: nadam
weight_init:
  value: he
