wandb_version: 1

activation:
  value: ReLU
alpha:
  value: 0.0001
batch-size:
  value: 16
beta_1:
  value: 0.9
hidden_sizes:
  value: 32
n_epochs:
  value: 5
num_layer:
  value: 4
optimizer:
  value: nesterov
weight-init:
  value: Xavier
