wandb_version: 1

activation:
  value: ReLU
alpha:
  value: 0.0001
batch-size:
  value: 32
beta_1:
  value: 0.9
hidden_sizes:
  value: 64.128
n_epochs:
  value: 10
num_layer:
  value: 5
optimizer:
  value: rmsprop
weight-init:
  value: random
