wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716201340
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      - 61
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
activation:
  desc: null
  value: tanh
alpha:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
beta1:
  desc: null
  value: 0.99
epochs:
  desc: null
  value: 10
hidden_sizes:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.01
loss:
  desc: null
  value: cross_entropy
num_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: sgd
weight_init:
  desc: null
  value: he
