wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.001
batch-size:
  value: 64
beta_1:
  value: 0.9
hidden_sizes:
  value: 64.128
loss_fn:
  value: cross_entropy
n_epochs:
  value: 10
num_layer:
  value: 4
optimizer:
  value: nadam
weight-init:
  value: random
