wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.0001
batch-size:
  value: 16
beta_1:
  value: 0.99
hidden_sizes:
  value: 64.128
loss_fn:
  value: cross_entropy
n_epochs:
  value: 10
num_layer:
  value: 3
optimizer:
  value: nesterov
weight-init:
  value: Xavier
