wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.001
batch-size:
  value: 16
beta_1:
  value: 0.9
hidden_sizes:
  value: 32
n_epochs:
  value: 10
num_layer:
  value: 5
optimizer:
  value: sgd
weight-init:
  value: random
