wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716257834
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      - 61
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
