wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.001
batch-size:
  value: 64
beta_1:
  value: 0.99
hidden_sizes:
  value: 64.128
loss_fn:
  value: cross_entropy
n_epochs:
  value: 5
num_layer:
  value: 5
optimizer:
  value: sgd
weight-init:
  value: Xavier
