wandb_version: 1

activation:
  value: ReLU
alpha:
  value: 0.001
batch-size:
  value: 32
beta_1:
  value: 0.9
hidden_sizes:
  value: 64
loss_fn:
  value: cross_entropy
n_epochs:
  value: 5
num_layer:
  value: 4
optimizer:
  value: nadam
weight-init:
  value: random
