wandb_version: 1

activation:
  value: ReLU
alpha:
  value: 0.0001
batch-size:
  value: 32
beta_1:
  value: 0.99
hidden_sizes:
  value: 32
n_epochs:
  value: 10
num_layer:
  value: 4
optimizer:
  value: nadam
weight-init:
  value: Xavier
